### ISSUE TITLE
Error creating Apigee drupal 8 kickstart project

### ISSUE THREAD

**Issue by huilinks** [apigee/apigee-devportal-kickstart-drupal#444]
## Description
When I use the following command to create Apigee kickstart drupal, 
c:\temp>composer create-project apigee/devportal-kickstart-drupal-8.x-1.x myproject

I get the following error.

  [Composer\Downloader\TransportException]
  curl error 60 while downloading https://packages.drupal.org/8/packages.json: SSL certificate problem: self signed certificate in certificate chain

## Steps to Reproduce
run composer with the above create-project command

## Actual Behavior
SSL certificate problem occurs

## Expected Behavior
Apigee Drupal 8 is installed successfully.

## Screenshots
![image](https://user-images.githubusercontent.com/76076562/102285075-167df900-3efb-11eb-999c-fc9d270c6469.png)

**Comment by kscheirer** [comment]
This is a composer/php configuration issue, not related to kickstart. Can you try some of the advice from https://stackoverflow.com/questions/21114371/php-curl-error-code-60? It seems like this should solve it
1. Copy this certificate bundle on your disk - https://curl.haxx.se/ca/cacert.pem
2. add `curl.cainfo = "path_to_cert\cacert.pem"` to php.ini

**Comment by cnovak** [comment]
Thanks @kscheirer for helping w/this issue! Will close it, but add a comment if there are still issues.

**Comment by huilinks** [comment]
I am still seeing the same error after I download the certificate and add
to my php.ini file

**Comment by huilinks** [comment]
I am able to download Drupal 8 without any issues (
https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies#download-core
)
composer create-project drupal/recommended-project my_site_name_dir

**Comment by huilinks** [comment]
![image](https://user-images.githubusercontent.com/76076562/103955455-f01f3800-510b-11eb-8264-9a3da93d6ff0.png)
